name: CI Workflow

on: [push]

jobs:
  build-and-run:

    services:
      dremio:
        image: ghcr.io/rsvihladremio/dremio-oss-test-image:0.1.0
        ports:
          - 9047:9047

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build, Setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Verify build
      run: ./scripts/build

    - name: Run tests
      run: ./scripts/test && ./scripts/cover

    - name: Run linting
      run: ./scripts/lint
